// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as AwsAppsync from "aws-appsync";
import * as Js_null_undefined from "bs-platform/lib/es6/js_null_undefined.js";

var config = {
  graphqlEndpoint: "https://h25cvu6lonfilcrryg7xo5fjne.appsync-api.eu-west-1.amazonaws.com/graphql",
  region: "eu-west-1",
  authenticationType: "API_KEY",
  apiKey: "da2-wj6ugvlymbhyzayd3t6ri3gcwi"
};

var AppSyncConfig = /* module */[/* config */config];

function createAWSAppSyncClient(url, region, auth, _) {
  return new AwsAppsync.AWSAppSyncClient({
              url: Js_null_undefined.fromOption(url),
              region: Js_null_undefined.fromOption(region),
              auth: Js_null_undefined.fromOption(auth)
            });
}

var AppSync = /* module */[/* createAWSAppSyncClient */createAWSAppSyncClient];

export {
  AppSyncConfig ,
  AppSync ,
  
}
/* aws-appsync Not a pure module */
