// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as AWS from "./AWS.bs.js";

var client = AWS.AppSync[/* createAWSAppSyncClient */0](/* Some */[AWS.AppSyncConfig[/* config */0].graphqlEndpoint], /* Some */[AWS.AppSyncConfig[/* config */0].region], /* Some */[{
        type: AWS.AppSyncConfig[/* config */0].authenticationType,
        apiKey: AWS.AppSyncConfig[/* config */0].apiKey
      }], /* () */0);

export {
  client ,
  
}
/* client Not a pure module */
